apiVersion: v2
name: freshrss
version: 0.1.0
appVersion: 1.16.2
description: A free, self-hostable aggregator… 
keywords:
  - freshrss
  - php
  - feed
  - rss
  - rss-aggregator
  - news-aggregator
  - self-hosted
  - rss-reader
  - websub
home: https://www.freshrss.org/
icon: https://raw.githubusercontent.com/FreshRSS/FreshRSS/master/docs/img/FreshRSS-logo.png
sources:
  - https://github.com/FreshRSS/FreshRSS
type: application
dependencies:
- name: postgresql
  version: "9.1.4"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
